### ISSUE TITLE
AttributeError: module 'jedi' has no attribute 'Script'

### ISSUE THREAD

**Issue by wookayin** [ncm2/ncm2-jedi#9]
The following error occurs, autocompletion not working:

```
[ncm2_jedi@yarp] AttributeError: module 'jedi' has no attribute 'Script'
```

vimrc:

```
Plug 'roxma/nvim-yarp'
Plug 'ncm2/ncm2'
Plug 'ncm2/ncm2-jedi'
Plug 'ncm2/ncm2-bufword'
autocmd BufEnter * call ncm2#enable_for_buffer()
```

messages:

```
[ncm2_jedi@yarp] Traceback (most recent call last):
[ncm2_jedi@yarp]   File "/home/XXXX/.vim/plugged/nvim-yarp/pythonx/yarp.py", line 30, in on_notification
[ncm2_jedi@yarp]     getattr(module_obj, method)(*args)
[ncm2_jedi@yarp]   File "/home/XXXX/.vim/plugged/ncm2/pythonx/ncm2.py", line 206, in on_complete
[ncm2_jedi@yarp]     on_complete_impl(context, *args)
[ncm2_jedi@yarp]   File "/home/XXXX/.vim/plugged/ncm2-jedi/pythonx/ncm2_jedi.py", line 40, in on_complete
[ncm2_jedi@yarp]     script = jedi.Script(src, lnum, len(typed), path)
[ncm2_jedi@yarp] AttributeError: module 'jedi' has no attribute 'Script'
```

A solution that worked:

**Reinstall `jedi` in the host python3 (`g:python3_host_prog`)** via pip, and the error is gone. Not sure why module `jedi` had pointed to a wrong (maybe old) version previously.

Unfortunately it is documented nowhere and error handling seems not robust. For example, we may detect `jedi` is well installed and import-able using the host python3 interpreter, and warn users if not.

Any other thoughts how we can improve this, as many users might experience this error?

**Comment by cbcoutinho** [comment]
I got the same error, and solved it by installing `jedi` into the python3 virtualenv I set up for neovim.

**Comment by gkapfham** [comment]
Hello @wookayin and @cbcoutinho, I wanted to write and let you know that I recently ran into this issue. I am currently running `NVIM v0.3.2-dev` on Ubuntu 16.04 and found that I also had to upgrade my installed version of `jedi`. After I did that, I found that `ncm2` and `ncm2-jedi` worked correctly. Perhaps it would be a good idea if there was some documentation to indicate which version of `jedi` was supported?

**Comment by sriramkswamy** [comment]
I got the same error but upgrading `jedi` didn't work. Can you let me know which version of `jedi` worked for you? I'm on `NVIM v0.3.1`

**Comment by vzxxbacq** [comment]
Install jedi in the host python3 (in a conda env) solved my problem (nvim 0.3.1), thanks.

**Comment by IliaOzhmegov** [comment]
Hey guys, I've just had the similar problem but it my case it was like this 
`[ncm2_jedi@yarp] AttributeError: 'Script' object has no attribute 'complete`.

and reinstalling via `pip3 install -I jedi` helped.
